### PR TITLE
prevent multiple apps from spawning

### PR DESCRIPTION
**Pull request by nhayfield**
## Summary
Prevents multiple instances of the app from opening at the same time

## Related issues
Fixes [#776](https://github.com/pomerium/internal/issues/776)

## Checklist

- [x] reference any related issues
- [ ] updated docs
- [ ] updated unit tests
- [ ] updated UPGRADING.md
- [ ] add appropriate tag (`improvement` / `bug` / etc)
- [x] ready for review

### CODE REVIEW

**Comment by wasaga** [comment]
review is pending as I need get to a windows machine to verify.

**Comment by alexfornuto** [comment]
:hand: I have a Windows machine, I could test it.

**Comment by travisgroth** [comment]
@nhayfield - @alexfornuto was able to test yesterday and this works as expected on windows.

**Comment by nhayfield** [comment]
https://github.com/pomerium/desktop-client/pull/108 was easier to redo then fix merge conflict

**Pull request closed without merging**
